name: samurai
services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=samurai'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=samurai'
    volumes:
      - C:\Users\Youcode\Desktop\pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres_data:
    driver: local